# name: model-training-evaluate
# on: [push]
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     container: docker://dvcorg/cml-py3:latest
#     steps:
#       # - uses: actions/checkout@v2
#       - uses: conda-incubator/setup-miniconda@v2
#         with:
#           auto-activate-base: true
#           activate-environment: ""
#       - name: 'Train and Evaluate model'
#         shell: bash
#         env:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         run: |
#           # Install requirements
#           conda env create -f environment.yaml
#           conda run -n mlops-digits dvc pull --run-cache

#           # Pull data & run-cache from S3 and reproduce pipeline
          
#           conda run -n mlops-digits dvc repro

#           # Report metrics
#           echo "## Metrics" >> report.md
#           git fetch --prune
#           conda run -n mlops-digits dvc metrics diff master --show-md >> report.md

#           # Publish confusion matrix diff
#           echo -e "## Plots\n### ROC Curve" >> report.md
#           cml-publish ./results/roc_curve.png --md >> report.md
#           echo -e "\n### Precision and Recall Curve" >> report.md
#           cml-publish ./results/precision_recall_curve.png --md >> report.md
#           cml-send-comment report.md
